### ISSUE TITLE
The problem of reuse

### ISSUE THREAD

**Issue by gentlezxz** [Yuzeyang/GCCardViewController#1]
I use it in my project by dragging. but if I add a View(eg: button) in ViewController, the problem of reuse is happen.
![problem](https://cloud.githubusercontent.com/assets/13794117/16408295/a7592100-3d4a-11e6-83b6-2bccda2727ca.gif)

**Comment by Yuzeyang** [comment]
@gentlezxz can you show how you add a view in ViewController? I add a button ,but it's ok

**Comment by gentlezxz** [comment]
I create a new project. Dot't let ViewController as Root, create a new ViewController push or present in ViewController. The problem still happen. 
In viewDidLoad, I add a button in self.view

**Comment by Yuzeyang** [comment]
ye,i update my demo,i was wrong,i shoud not create cards in viewDidLayoutSubviews method, it will be called many times,it should be called in viewWillAppear，thank you~

**Comment by gentlezxz** [comment]
yeah, It's ok!

**Comment by gentlezxz** [comment]
Excuse me, I want to translate the current Card'y when scroll, how can I do? I use the Progress but progress is between 0 to 0.7 then jump to 0.13.

**Comment by Yuzeyang** [comment]
because when the cards scroll 80% of distance,i update the card index, so progress is between 0 to 0.7 then jump to 0.13.but it still ok, you can  translate card in `- (void)updateCard:(UIView *)card withProgress:(CGFloat)progress direction:(CardMoveDirection)direction` delegate, change the layer

**Comment by gentlezxz** [comment]
Thank you very much!
I have done it In your way, Have a good effect！
Just have a small problem, In the process of sliding there has a jump obviously when the translate is longer.

**Comment by Yuzeyang** [comment]
can you show your translate code?

**Comment by gentlezxz** [comment]
I magnified 50 times.
- (void)updateCard:(BaseView *)card withProgress:(CGFloat)progress direction:(CardMoveDirection)direction {
    CGFloat scale1 = 1 - 0.5 * progress;
    CGFloat scale2 = 0.5 + 0.5 * progress;
    if (direction == CardMoveDirectionNone) {
        if (card.tag != [self.cardScrollView currentCard]) {
//            card.layer.transform = CATransform3DMakeScale(scale, scale, 1.0);
            card.layer.transform = CATransform3DMakeTranslation(0, scale2 * 50, 0);
            card.layer.opacity = 1 - 0.2*progress;
        } else {
//            card.layer.transform = CATransform3DIdentity;
            card.layer.transform = CATransform3DMakeTranslation(0, scale1 * 50, 0);
            card.layer.opacity = 1;
        }
    } else {
        NSInteger transCardTag = direction == CardMoveDirectionLeft ? [self.cardScrollView currentCard] + 1 : [self.cardScrollView currentCard] - 1;
        if (card.tag != [self.cardScrollView currentCard] && card.tag == transCardTag) {
//            card.layer.transform = CATransform3DMakeScale(0.9 + 0.1*progress, 0.9 + 0.1*progress, 1.0);
            card.layer.transform = CATransform3DMakeTranslation(0, scale1 * 50, 0);
            card.layer.opacity = 0.8 + 0.2*progress;
        } else if (card.tag == [self.cardScrollView currentCard]) {
//            card.layer.transform = CATransform3DMakeScale(1 - 0.1 * progress, 1 - 0.1 * progress, 1.0);
            card.layer.transform = CATransform3DMakeTranslation(0, scale2 * 50, 0);
            card.layer.opacity = 1 - 0.2*progress;
        }
    }
}

**Comment by gentlezxz** [comment]
I magnified 50 times.
- (void)updateCard:(BaseView _)card withProgress:(CGFloat)progress direction:(CardMoveDirection)direction {
  CGFloat scale1 = 1 - 0.5 \* progress;
  CGFloat scale2 = 0.5 + 0.5 \* progress;
  if (direction == CardMoveDirectionNone) {
      if (card.tag != [self.cardScrollView currentCard]) {
  //            card.layer.transform = CATransform3DMakeScale(scale, scale, 1.0);
          card.layer.transform = CATransform3DMakeTranslation(0, scale2 \* 50, 0);
          card.layer.opacity = 1 - 0.2_progress;
      } else {
  //            card.layer.transform = CATransform3DIdentity;
          card.layer.transform = CATransform3DMakeTranslation(0, scale1 \* 50, 0);
          card.layer.opacity = 1;
      }
  } else {
      NSInteger transCardTag = direction == CardMoveDirectionLeft ? [self.cardScrollView currentCard] + 1 : [self.cardScrollView currentCard] - 1;
      if (card.tag != [self.cardScrollView currentCard] && card.tag == transCardTag) {
  //            card.layer.transform = CATransform3DMakeScale(0.9 + 0.1_progress, 0.9 + 0.1_progress, 1.0);
          card.layer.transform = CATransform3DMakeTranslation(0, scale1 \* 50, 0);
          card.layer.opacity = 0.8 + 0.2_progress;
      } else if (card.tag == [self.cardScrollView currentCard]) {
  //            card.layer.transform = CATransform3DMakeScale(1 - 0.1 \* progress, 1 - 0.1 \* progress, 1.0);
          card.layer.transform = CATransform3DMakeTranslation(0, scale2 \* 50, 0);
          card.layer.opacity = 1 - 0.2_progress;
      }
  }
  }

**Comment by Yuzeyang** [comment]
i know the reason, when the `direction == CardMoveDirectionNone`, you should set the `transform` as same as the `direction == CardMoveDirectionLeft` or `direction == CardMoveDirectionRight`

i modify the `direction == CardMoveDirectionNone` code,you can try it

``` objective-c
if (direction == CardMoveDirectionNone) {
    if (card.tag != [self.cardScrollView currentCard]) {
        card.layer.transform =
        CATransform3DMakeScale(0.9 + 0.1*progress, 0.9 + 0.1*progress, 1.0);
      card.layer.transform = CATransform3DMakeTranslation(0, scale2 * 50, 0);
      card.layer.opacity = 1 - 0.2*progress;
    } else {
        card.layer.transform =
        CATransform3DMakeScale(1 - 0.1 * progress, 1 - 0.1 * progress, 1.0);
      card.layer.transform = CATransform3DMakeTranslation(0, scale1 * 50, 0);
      card.layer.opacity = 1;
    }
  }
```

**Comment by gentlezxz** [comment]
Yeah! It's OK! 
I change the kGCRatio, then I must change the progress In - (void)scrollViewDidScroll:(UIScrollView *)scrollView
Thank you very much!

**Comment by Yuzeyang** [comment]
That's all right.😃~
